version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6.5
     steps:
       - checkout
       - run: python helloWorld.py
       - run: echo "echo statement"
workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
